### ISSUE TITLE
It doesn't detect words at the end of a document

### ISSUE THREAD

**Issue by webguy24** [InternetRamen/word-checker#2]
I tested with "happy sad good mad bad nice stuff thing very extremely fast slow long short amazing love funny heart soul a lot pretty fun smile based off flower" and it didn't detect the word "flower". Tried it multiple times with other strings as well and it always failed to detect the last word.

**Comment by InternetRamen** [comment]
Sorry! I didn't see this until just now. I'll link a pull request tomorrow.

**Comment by InternetRamen** [comment]
I tried this string with the same code and got: 
![image](https://user-images.githubusercontent.com/66806100/150905534-6ce9bbf2-9419-4553-bb88-a0afa4866266.png)

Could you give me the other strings you tried and some screenshots?

**Comment by webguy24** [comment]
It seems like it only misses the final word if there's no space immediately following it (i.e a newline). Try the string I used but with newlines instead of spaces

**Comment by InternetRamen** [comment]
Fixed!
